### ISSUE TITLE
3rd party domains are not all enabled on fresh site visit

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#109]
As discussed in our meeting, we noticed that on a clean browser install, our popup seemed to show that certain third party domains on the NYTimes site were not shown as enabled (in other words, the checkmark was not checked). Let's use this issue to resolve this problem.

**Comment by kalicki1** [comment]
During our meeting today, we found that my GitHub was not loading all subdomains properly. Let's look into this. 
![Screen Shot 2020-11-17 at 3 00 42 PM](https://user-images.githubusercontent.com/60238705/99441363-bee17300-28e5-11eb-9efb-d3f6cee97c39.png)

**Comment by SebastianZimmeck** [comment]
We received one [new review on the Chrome Web Store](https://chrome.google.com/webstore/detail/optmeowt/hdbnkdbhglahihjdbodmfefogcjbpgbo), and it may relate to this issue. The review (in Italian) says:

> ottima estensione, però nelle impostazioni quando clicco "enable" tra le tre impostazioni, certe volte su certi siti ritorna su "domain list" senza aver cliccato nulla

Per Google Translate:

> excellent extension, but in the settings when I click "enable" between the three settings, sometimes on certain sites it returns to "domain list" without clicking anything

Maybe, this is also a different issue, but I am not quite sure. We could reply to the review. Let me know what you think.

**Comment by SebastianZimmeck** [comment]
The previous comment is related to issue #127.

**Comment by dknopf** [comment]
I don't think that this problem is limited to a clean browser install, as I am having this issue even using my already installed version of chrome with optmeowt installed. I did have optmeowt disabled for a little while before testing this, but even after multiple visits to a site, such as github, I am still getting the above third party sites are disabled

**Comment by dknopf** [comment]
It seems that the cause of this problem was that we were filtering out any request that was of type "image," which Kuba tells me was intentional and related to a previous issue. Redirects that were used to load images, such as Github's redirect to their avatars.githubusercontent.com site, wouldn't be included in the domain list as they were of type image. By removing that restriction, I was able to successfully send the GPC header to all third party domains. 

However, there is another issue that is causing some of the third party domains to still show as disabled in the optmeowt popup. I believe that while the extension correctly identifies all third-party domains and attempts to add them to the domain list, the Chrome storage API [isn't fast enough](https://developer.chrome.com/docs/extensions/reference/storage/#storage-and-throttling-limits) to upload all the domains. Therefore, some third-party domains don't end up getting added to the domain list because the storage upload process is interrupted by another upload process. Therefore, when the popup identifies all domain requests made of it, it finds the third party domains that weren't uploaded to chrome storage domain list and marks them as disabled because they aren't in the domain list.

However, these domains have actually been enabled, because even though they aren't uploaded, the GPC header is still added to them. For example, on [humble bundle](https://www.humblebundle.com/?hmb_source=navbar) the taboola.com domain is sent the GPC signal, but it shows up as disabled in the popup. 

![image](https://user-images.githubusercontent.com/7244624/103184115-77ef8180-4884-11eb-8ad3-ee6c4100c4f7.png)

Some of the reasons for this bug diagnosis are that its clear from my debugging that the domains are being correctly detected and should be added, so the problem is with adding them to the domain list. Additionally, after just refreshing a site a few times more and more domains get correctly enabled in a random manner, which makes it likely that whichever domain is lucky enough to make it through the upload process gets added to the domain list, and the domains that show up more often usually show up quicker than the domains that only send one request.

I'm working on a solution to fix the failed upload of domains to the domain list, which will probably involve either preventing the program from querying what the domain list is until the current upload is finished, or keeping some sort of domain list variable locally and then adding all the domains to chrome storage after all the domains have been checked.

**Comment by SebastianZimmeck** [comment]
> By removing that restriction, I was able to successfully send the GPC header to all third party domains.

Excellent! Yes, the original idea was that there is no point to send opt out requests to servers that simply serve images or other assets. But in the end it does not really matter, we can just send them.

> However, there is another issue that is causing some of the third party domains to still show as disabled in the optmeowt popup. ... I'm working on a solution to fix the failed upload of domains to the domain list ...

Great detective work on that one, @dknopf. Perhaps, some [asynchronous calls](https://www.pluralsight.com/guides/introduction-to-asynchronous-javascript) could be used (random link to the tutorial; not sure if it is good).

**Comment by dknopf** [comment]
Created a fix in pull request #129 , awaiting review.
