### ISSUE TITLE
Fix anything outstanding for Firefox release

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#110]
As @kalicki1 and @asalia-1 explained there may be one or the other minor issue or testing task to be done for our Firefox release. I am opening this issue as an omnibus issue of sorts for all those tasks. @kalicki1 is in the lead on this one and will confer with @asalia-1.

**Comment by asalia-1** [comment]
We worked on a fix for the popup to get rid of scroll bar in the popup when rendering in Firefox. We also fixed a bug in the options page that was causing inability to switch to the domainlist and about page due to one library. After fixing theses bugs, we tested manually to make sure core functionality for Firefox works as it should.  Current version in master is Firefox ready

**Comment by kalicki1** [comment]
As @asalia-1 mentioned, we finalized our work for the Firefox release as planned. We will open a new issue given the issues my specific version of Firefox (computer in general) saw when we tested in our meeting, and we can discuss solutions there. When that is resolved, we can push to the Firefox store.
