### ISSUE TITLE
Add functionality to analyze and display the content of .well-known responses

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#125]
@kalicki1 already implemented functionality for detecting whether a site has a .well-known site, in which case OptMeowt shows in the popup that the GPC signal is accepted by the site (issue #116). However, the .well-known site may have more nuances than just saying that the GPC signal is accepted. For example, they could say that it is accepted for users from California but not for users from other states or countries. Thus, ultimately, we want to analyze and display the content of the .well-known file going beyond just detecting it. As this functionality depends a lot on what sites actually decide to implement, this issue is a longer term issue with low priority at the moment. However, once more sites implemented their response, we should come back to it.

**Comment by SebastianZimmeck** [comment]
Maybe, to get started, just display the contents of the JSON response under a similar collapsable tab similar to "3rd Party Domains"

<img width="337" alt="Screen Shot 2020-12-21 at 11 27 56 AM" src="https://user-images.githubusercontent.com/11034003/102798791-971b7a00-437f-11eb-88a6-5d72ae8bf172.png">

**Comment by SebastianZimmeck** [comment]
For the time being, let's just surface whatever content is in the JSON under a collapsable tab per above.

**Comment by kalicki1** [comment]
I created the basic system for displaying our .well-known information from within the popup. Here is a screenshot of how it looks at the moment: 

<img width="374" alt="Screen Shot 2021-01-13 at 3 56 49 PM" src="https://user-images.githubusercontent.com/60238705/104509988-7f1ecb00-55b8-11eb-8a38-c6c12c1f5208.png">

I will clean up the design and how the JSON file is displayed (to make it more user friendly) and will push the changes once they are finalized. @SebastianZimmeck @dknopf let me know if you all have any design suggestions!

**Comment by SebastianZimmeck** [comment]
That's solid.

**Comment by kalicki1** [comment]
I just pushed changes that update the displayed text and popup dropdown tabs when OptMeowt finds .well-known info on a particular site. Here are screenshots of the two current cases we check for : 

<img width="341" alt="Screen Shot 2021-01-15 at 3 18 05 PM" src="https://user-images.githubusercontent.com/60238705/104775193-f59d0380-5745-11eb-8e91-df28efcd0e4d.png">
<img width="348" alt="Screen Shot 2021-01-15 at 3 18 20 PM" src="https://user-images.githubusercontent.com/60238705/104775199-f6ce3080-5745-11eb-8290-a27f1819d621.png">

We could leave this as is, though I feel it is a little bit clunky. What I am thinking is that I will take the title inside the dropdown and have it auto-generate a title on the dropdown tab clicker, so that instead of `Website Response`, the tab will say one of three things: `GPC Signals Accepted`, `GPC Signals Denied`, or `GPC Policy Missing`. The only thing about this is that it could imply the GPC signals were sent and accepted by the site when a user chooses not to send signals to that particular site, though this dropdown is only intended to inform the user that the website does potentially accept signals if they are sent (per how the .well-known spec is designed). 

As a side note, I added a case in the current commit that will show the policy no matter what is written in it even if the site expresses it will not respect signals. In this case the `GPC Policy Missing / Denies Request` text will show alongside the policy, though I don't expect this to be a common case by any means.

**Comment by SebastianZimmeck** [comment]
Looks good!

>  What I am thinking is that I will take the title inside the dropdown and have it auto-generate a title on the dropdown tab clicker, so that instead of Website Response, the tab will say one of three things: GPC Signals Accepted, GPC Signals Denied, or GPC Policy Missing

OK, sounds good. Per the [spec](https://globalprivacycontrol.github.io/gpc-spec/#gpc-support-representation),  GPC Signals Accepted is `true`, GPC Signals Denied is `false`, and GPC Policy Missing if there is no resource.
