### ISSUE TITLE
Better handling of extension conflicts, other injection tweaks

### ISSUE THREAD

**Issue by dharb** [privacy-tech-lab/optmeowt-browser-extension#128]
Just wanted to keep you guys up to date with a couple edits we made to our implementation after observing it in production. I updated the implementation guidance [doc](https://github.com/globalprivacycontrol/gpc-implementation-guidance/blob/main/client-implementation.markdown) with these changes, but wanted to explain them as well.

### Handling extension conflicts
This is a minor issue that came up [here](https://github.com/globalprivacycontrol/gpc-spec/issues/11#issuecomment-736772505). Users can have multiple extensions installed that are trying to set the Global Privacy Control DOM value. We want to be sure that if a different extension is setting GPC to true, we don't override it with false. Check out the edits to https://github.com/globalprivacycontrol/gpc-implementation-guidance/blob/main/client-implementation.markdown#gpcjs and https://github.com/globalprivacycontrol/gpc-implementation-guidance/blob/main/client-implementation.markdown#gpc-mozjs to see how this can be done.

### Injection into non-html pages
It turns out that Chrome will inject content script tags into non-html pages, which can cause the script text to appear in the content. To avoid this, we specifically check to make sure that the content type of the page isn't xml, json, or rss. See edits to https://github.com/globalprivacycontrol/gpc-implementation-guidance/blob/main/client-implementation.markdown#gpcjs for fix.

### Injecting multiple times per frame
I came across a couple sites that managed to trigger injection multiple times per iframe. It turns out this can happen when sites add a blank iframe to the page first, then update the iframe location. This causes onCommitted to be fired multiple times for these frames, which then triggers the content scripts to be injected into all frames each time. The solution is specify which frame the content script should be injected into (rather than `allFrames`). See https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/523/files for details.

Hope this is helpful, and my apologies for not catching these the first go round.

**Comment by SebastianZimmeck** [comment]
Thanks so much, @dharb! We will look into these ...

**Comment by kalicki1** [comment]
Thanks for the updates @dharb, they're much appreciated! 

@SebastianZimmeck, I went through and updated our source code as applicable, I have the changes in branch `issue-128`. I will open a pull-request to bring the changes in. 

### Some notes for myself: 

With regards to the DOM property extension conflicts, I added the extra check for `navigator.globalPrivacyControl === true` before setting our own, though we only ever set our DOM property if the user does in fact want to send the signal to the first party domain. Hence, it doesn't do much at the moment, since we would only ever override a prior signal with our intent to set `navigator.globalPrivacyControl = true`. In the future we can update our signal in accordance with the spec and set a `false` when the user does not want to send the GPC signal, though this will take some code revamping. (This is the same for our Mozilla version.) For the moment, I think it is okay to leave it as it is.

**Comment by SebastianZimmeck** [comment]
Excellent, @kalicki1!

Feel free to close this issue if it is resolved.
