### ISSUE TITLE
Disabling a site's domain logs you out of that site

### ISSUE THREAD

**Issue by dknopf** [privacy-tech-lab/optmeowt-browser-extension#130]
I just noticed that when I disable the "google.com" domain, either the third party one or the main one on google.com, it logs me out of all my Google accounts.

![image](https://user-images.githubusercontent.com/7244624/103469906-0490b880-4d39-11eb-8380-c08a24878678.png)

**Comment by SebastianZimmeck** [comment]
Interesting. Is that Google-specific or does that also happen with accounts from other domains (e.g., Facebook)?

**Comment by dknopf** [comment]
It seems to be happening with all sites I try, such as Github, Facebook, nytimes.com, and Humblebundle.com.

**Comment by SebastianZimmeck** [comment]
Ah, OK. Well, I guess, that could pass as a feature instead of a bug. ☺️ 

I could imagine that this may be difficult to resolve because it may be that once a site realizes changes in the header, it logs a user out for security reasons (not sure if that is really the case, but I could imagine it). So, the best we may be able to do is to notify users of this behavior in the OptMeowt settings, the readme, a Wiki, or elsewhere.

**Comment by SebastianZimmeck** [comment]
@kalicki1, if you could provide a small explanation in the Wiki, reference this issue, and that should be it.
