### ISSUE TITLE
Create tutorials on GPC frontend implementation [OptMeowt as frontend reference implementation]

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#134]
As we discussed today, in addition to a working user tool, OptMeowt can serve as a template for implementing GPC in browsers and browser extensions. To that end, it may be helpful to:

- Rewrite the readme a bit to address developers
- Include additional info in the Wiki
- Create a blog post (e.g., we can publish it on Medium) with a tutorial and some code snippets on how to do it
- Have a video tutorial explaining the implementation and showing how it works
- maybe other or different things ...

(This can be done after February 4, the paper deadline.)

**Comment by kalicki1** [comment]
I created a new folder in branch issue-134, `src\implementation`, which contains a new barebones example Chrome extension. 

The new folder contains the `manifest.json` and `background.html` an extension requires at a minimum, however, the goal is to test whether we can have a single JS file that developers could drop into privacy-focused extensions in order to enable the GPC HTTP and DOM signals on every site visited. Though the code itself can still be refined just a little bit more, it is basically the skeleton signal-setting infrastructure from our OptMeowt extension itself. I went through and cut out the bells and whistles OptMeowt has. If we want we can discuss what other features an example implementation like this should have, such as adding back in an option to choose what websites to send signals to, though I left that out for now. 

Once we agree this is the way to go, then I plan to start working on articles on how to actually implement a "drop-in" JS file like the one I created, be it on a blog or our wiki or otherwise.

**Comment by kalicki1** [comment]
I created a sample Medium blog post that can serve as our frontend implementation reference for the time being. We can change platforms, I'm not partial to Medium, but that is where everything is for the time being. 

[Here is the Medium draft link.](https://medium.com/@kalicki/sample-frontend-implementation-for-global-privacy-control-gpc-6a8f568a61aa) 

It is still a work in progress, but let me know if you think anything could be improved or have any ideas!

**Comment by SebastianZimmeck** [comment]
Thanks, @kalicki1! This is a good start, though, fairly high-level. I was thinking of something more concrete. Think of a developer documentation, for example, like the [AdMob integration instructions](https://developers.google.com/admob/ios/quick-start). What is your opinion? Maybe, include code snippets, describe which pieces of code are responsible for which functionality, how those code pieces interact, etc. It does not need to be comprehensive but more like "If you want to implement the header, this is what you do ... if you want to implement the DOM, ... ." At the moment, I am thinking, we can just make that a big separate part in the readme here. So, that everything is together.

**Comment by SebastianZimmeck** [comment]
Closing this issue as it is superseded by #171.
