### ISSUE TITLE
"Extension Disabled" Text is Hidden Behind Scrim

### ISSUE THREAD

**Issue by dknopf** [privacy-tech-lab/optmeowt-browser-extension#137]
When I disable the optmeowt extension via the "disable" button at the top of the popup the subsequent "extension disabled" screen looks a bit weird as it seems the words "extension disabled" are hidden behind a white scrim instead of on top of it

![image](https://user-images.githubusercontent.com/7244624/107410465-5a484580-6adb-11eb-9c82-616674fe34cf.png)

**Comment by kalicki1** [comment]
Thanks for the heads up @dknopf! I just pushed an update fixing the issue, it looks like one of the "transparent" parent div tags didn't have a proper closing, so the "Extension Disabled" text was made transparent as well. I pushed the changes right to the main branch so I'll go ahead and close this issue since we should be all set with it!
