### ISSUE TITLE
Running on moz-extension scripts

### ISSUE THREAD

**Issue by sammypanda** [privacy-tech-lab/optmeowt-browser-extension#146]
OptMeowt is blocking some of my browser extensions (firefox) from reaching out to my computer :(

I'm not sure if there is a way to disable OptMeowt for local origins :heart:

**Comment by sammypanda** [comment]
sowwy, here are some more details :)

![image](https://user-images.githubusercontent.com/38725335/114166096-a47d6400-9970-11eb-9324-826ef6e2fdb9.png)
- you can pretty much ignore webrequest.js / ui-service.js, they are just scripts from that extension that are throwing errors in response to the blocks from the optmeowt scripts

**Comment by SebastianZimmeck** [comment]
Thanks for pointing this out, @sammypanda! We will be looking into that. Could you provide some more information so that we can try reproducing the error? For example, which other extensions are involved, any particular settings you have on those, ...

**Comment by sammypanda** [comment]
I have this as the server on my desktop https://github.com/lolamtisch/Discord-RPC-Extension/releases/tag/0.1.2

this as the hook in my browser https://addons.mozilla.org/en-US/firefox/addon/discord-rich-presence/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser

and this to interact with the hook extension https://addons.mozilla.org/en-US/firefox/addon/prewrap/

**Comment by SebastianZimmeck** [comment]
Thank you @sammypanda, we will look into this (may take a while but we are on it ...)

**Comment by kbeliauski** [comment]
@sammypanda our extension is trying to update the cookies in your local file, but as far as I know, Firefox doesn't let us update cookies in local files, so that's why you are getting these errors from our side. Does everything works once you turn off OptMeowt? Also, could you please describe what you are trying to do with those extensions that you mentioned? It looks like you are using a wrapper for PreMiD to update your Discord status based on what you are doing in the browser.

**Comment by kbeliauski** [comment]
I installed all of those extensions and added some presences to PreWrap, and everything works for me (with OptMeOwt on)

**Comment by kbeliauski** [comment]
Hey, @sammypanda ! I am closing this issue since we haven't heard from you back in a week, but feel free to open it back up if something comes up.
