### ISSUE TITLE
Look into decrypting HTTPS traffic

### ISSUE THREAD

**Issue by stanleymarkman** [privacy-tech-lab/optmeowt-browser-extension#161]
This is a somewhat urgent issue- HTTPS ad call requests are currently encrypted and hidden to us. We need to look more into this and see if it's possible to decrypt on Chrome- Raf found some way to do this on Firefox, so this might need to be browser-specific functionality.

**Comment by SebastianZimmeck** [comment]
@rgoldstein01, @davebaraka, and @notowen333, I just discussed with @stanleymarkman and @kbeliauski that decrypting HTTPS requests is only possible on Firefox. @stanleymarkman mentioned that there is an official Firefox API as part of their tracking protection functionality. Is that what we are using in the integrated privacy analysis?

Chrome was a dead end, right? Have we tried anything there?

**Comment by SebastianZimmeck** [comment]
@stanleymarkman describes the Firefox functionality in issue #162.

**Comment by rgoldstein01** [comment]
@SebastianZimmeck Correct. That is what we are using.

**Comment by SebastianZimmeck** [comment]
Thanks, @rgoldstein01!

@stanleymarkman and @kbeliauski, I just added you to the integrated-privacy-analysis repo where @rgoldstein01, @davebaraka, and @notowen333 implemented the Firefox API. If you search for the API via the search box in the repo, you should be able to find it and see how it is used (if at all helpful).

integrated-privacy-analysis is a browser extension based on React and for Firefox that also needs to decrypt requests. The analysis of the requests is broader, e.g., checking whether location data is shared as opposed to checking for privacy setting flags. But the underlying problem is the same: how to look into encrypted requests?

**Comment by SebastianZimmeck** [comment]
I am closing this. Basically, decrypting HTTPS with Chrome is too complicated, and we only implement the analysis functionality for Firefox.
