### ISSUE TITLE
[Bug] Extension is using way too much memory

### ISSUE THREAD

**Issue by unbeatable-101** [privacy-tech-lab/optmeowt-browser-extension#164]
https://bugzilla.mozilla.org/show_bug.cgi?id=1708506

**Comment by SebastianZimmeck** [comment]
Thank you, @unbeatable-101! We will look into that. We are in the process of restructuring the architecture of OptMeowt, and will address this issue along the way.

From the linked thread above:

> I could not reproduce the issue on the latest Nightly (90.0a1/20210503214210) under Windows 10 x64.

> I tested both with and without the extensions installed (OptMeowt).

> Without the extension installed, overall memory usage was around 1.2 GB of RAM with the WebExtensions process spiking to a maximum of 120-150 MB.

> With the extensions installed, overall memory usage spiked at around 2.8 GB several times, but returned to around 1.2 GB memory usage (as without the add-on installed). The WebExtensions process spiked to ~300 MB but not more, at the same time the overall memory usage was higher. It returned to under 100 MB when the overall memory usage got lower.

**Comment by SebastianZimmeck** [comment]
I looked into this issue and running the current OptMeowt build from source on Firefox (90.0.2 (64-bit)) with a few tabs open, including a YouTube video, uses about 600 MB for the whole browser. There do not seem to be any spikes in memory usage. The same for Brave. Maybe, our use of IndexedDB took care of the issue. If the problem comes up again, we can reopen this issue or create a new one.
