### ISSUE TITLE
Replacing local storage with IndexedDB

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#170]
Let's use this issue to research whether or not it is worth implementing a local database for our data instead of using local storage (as we currently use). In my eyes we can work on this when we have some time, although implementing this might help with resource management and codebase clarity in general.

**Comment by SebastianZimmeck** [comment]
Yes, if one of you, @stanleymarkman or @kbeliauski, can take the lead here. Here is an explanation on [IndexedDB](https://developers.google.com/web/ilt/pwa/working-with-indexeddb).

**Comment by kbeliauski** [comment]
@SebastianZimmeck, I can totally read up on IndexedDB and figure out how it can help us.

**Comment by SebastianZimmeck** [comment]
Great, @kbeliauski! Please also take a look at our codebase, and how IndexedDB fits in. @kalicki1 will be able to chime in.

**Comment by kalicki1** [comment]
As discussed yesterday, @kbeliauski will take the lead here and work on this issue on a branch of branch issue-166. Once completed, we will have to take care to rebase and merge back into the main branch. 

@kbeliauski, let us know if you find anything useful and write up what you find here. Let me know if you feel we will need to change the API in `storage.js` based on how indexedDB works.

**Comment by kbeliauski** [comment]
Figured out the reason why I could not see the database in the storage tab of the toolbox: google's website with the tutorial on the idb API is really outdated, so from now on I am just relying on the documentation from the jakearchibald/idb. The new version made the new library a module, which affects the way the new database is created. Also, I installed webpack on this branch.

**Comment by kbeliauski** [comment]
Since the functions in the event.js file are not connected to the listeners in background.js, and the the bundle that is created by webpack (i.e. background.bundle.js) changes the names of the functions that are imported to the original background.js file, and since we don't want to reconnect the functions from events.js to the listeners because it will mess up the new code with the old code, I am looking for a way to make webpack not change the names of the imported functions (which will allow me to debug the code using the console). In case that doesn't work, I am going to look at how to use SourceMaps with webpack, which allows me to see the actual origin of the code before it is all bundled.

**Comment by kbeliauski** [comment]
I have implemented the indexedDB functionality for the current functionality of the extension. Once we need to implement it in other places, I will reopen this issue.
