### ISSUE TITLE
Fix DOM property set for Chrome (refactored code)

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#174]

**Comment by SebastianZimmeck** [comment]
@kalicki1, could you provide a short update here? (or we can discuss later today)

**Comment by kalicki1** [comment]
I haven't tackled this fully yet, however the issue as it stands is that refactoring somehow broke the DOM property injection functionality on either Chrome or Firefox (I don't remember unfortunately). I just double checked to see which it is, and it seems like it may be broken for both now after adding Webpack into the workflow. For this issue, I have two recommendations for starting points: 

1. When we first implemented the DOM property, DDG recommended that we handle injection better with suggestions mentioned in issue #128. It may be good to review how we should handle differences in planting the DOM property for Chrome vs. Firefox.

2. It may also be good to change how we handle `dom.js`. Currently, its a standalone script that executes on call. We could implement it as an exported function we import immediately, but which we inject with `[tabs.executeScript](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript)` as a function rather than a file. As a side note, we may have to use a newer library (related to out manifest v3 issue #175) to replace the injection API we currently use.


This might be a good task for @kbeliauski when he finishes up with implementing our storage. Otherwise I can look into this.

**Comment by SebastianZimmeck** [comment]
Sounds good. Yes, a good issue for @kbeliauski (with your input).

**Comment by kbeliauski** [comment]
The DOM signal is being sent now. We fixed the problem by adding copying the dom.js file to the dev folder, which is a folder that webpack creates when building the project. We do this using CopyPlugin. The reason why we use this plugin is because we don't have that many files that need to be copied to the build folder. We can return back to this issue if at some point we realize that we have too many files to copy and the use of this plugin will not be efficient. The other way we would use the files we copy is by moving all of the files to some "inject" folder that would be copied over to the build using CopyPlugin (it would be just an organizational change that would make the code cleaner).

**Comment by SebastianZimmeck** [comment]
@kbeliauski, could you also add CopyPlugin to the [third party libraries list](https://github.com/privacy-tech-lab/optmeowt-browser-extension#third-party-libraries)? Let's do this in general for all dependencies. That way we have a central place, especially, if we want to review license agreements.

**Comment by kbeliauski** [comment]
@SebastianZimmeck, I will create a new issue for this since we have other dependencies that need to be added there. So I will go through he whole code and see what else was not added.
