### ISSUE TITLE
Update the Third Party Library List

### ISSUE THREAD

**Issue by kbeliauski** [privacy-tech-lab/optmeowt-browser-extension#188]
Since we refactored our code to use webpack, babel, and many other different third party dependencies, we need to update the [third party libraries list](https://github.com/privacy-tech-lab/optmeowt-browser-extension#third-party-libraries). I will just go through the code and add everything that is not in the list yet.

**Comment by SebastianZimmeck** [comment]
I am in the process of updating the list:
- Looks like we are not using [psl (Public Suffix List)](https://github.com/lupomontero/psl) anymore
- For the time being, I am leaving in Dark Mode Switch. If @OliverWang13 is not using it, we can remove it (and add whatever @OliverWang13 is using, if anything)
- I will add the following libraries:
   - [webpack](https://webpack.js.org/)
   - [babel](https://babeljs.io/)

@kalicki1 and @stanleymarkman, is the above correct? Also, am I missing any library that we have added in the meantime and not in the list yet?

Slightly off-topic, but are we still using grunt? Probably not, right? I tried the [install from source instructions](https://github.com/privacy-tech-lab/optmeowt-browser-extension#installing-and-running-optmeowt-from-source-on-chromium-based-browsers) and they do not work anymore.

**Comment by kalicki1** [comment]
@SebastianZimmeck, 

- We are still using [psl (Public Suffix List)](https://github.com/lupomontero/psl). We use it to parse incoming URLs to get its domain. 
- glob-parent is a dependency of one of our dependencies if I remember correctly, so I don't think we should list that directly


Leaving Dark Mode Switch and adding in webpack and babel sounds good to me. Generally I think it's okay to go by the package dependencies listed on our `package.json`, I don't think we use any libraries that aren't npm packages. Here is a [link to the dependencies](https://github.com/privacy-tech-lab/optmeowt-browser-extension/blob/main/package.json#L26) listed in our `package.json`. 

We also use a handful of dev dependencies, such as other webpack plugins, but I'm not sure to what extent we should include those. 

> Slightly off-topic, but are we still using grunt?

You're right, we are not. As discussed yesterday, our install instructions have since been updated.

**Comment by SebastianZimmeck** [comment]
OK, thanks, @kalicki1! I kept is simple and just linked from the readme to the package.json. That way we do not have the update in multiple places; only in the JSON (and make sure that the link in the readme remains correct).
