### ISSUE TITLE
Implement the DAA CCPA Opt Out Tool for the Web

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#42]
I just checked the [DAA CCPA Opt Out Tool for the Web](https://digitaladvertisingalliance.org/DAA_style/ADS/CCPA_Opt_Out_Tool_Technical_Description.pdf) (which doubles also as the NAI's opt out tool). 

In principle, the DAA solution is technology-agnostic (per the above link, "store the browser request through an opt out cookie or other technology"). However, in practice it is [implemented via an opt out page and third party cookies](https://optout.privacyrights.info/). While the IAB solution (issue #17) is intended for publishers, the DAA solution is for ad networks and other third parties. The third parties sign up and then they become part of the opt out page. Essentially, this means that we would need to get third party opt out cookies into a browser. I do not see a clear path how this could be done.

Also, the different third parties are using different cookie IDs and values. There does not seem to be any standardization. I took a fresh Chrome browser with all data deleted and opted out from a few ad networks, which set the following cookies.

<img width="347" alt="Screen Shot 2020-06-30 at 10 33 25 PM" src="https://user-images.githubusercontent.com/11034003/86196665-bd273680-bb21-11ea-9186-ab9c512906bf.png">

<img width="389" alt="Screen Shot 2020-06-30 at 10 34 31 PM" src="https://user-images.githubusercontent.com/11034003/86196749-e5169a00-bb21-11ea-985a-0a7211ca048c.png">

<img width="358" alt="Screen Shot 2020-06-30 at 10 35 33 PM" src="https://user-images.githubusercontent.com/11034003/86196822-0c6d6700-bb22-11ea-8bf7-e3875f54dbda.png">

These opt out domains are also unrelated to the ad server domains.

Unless there is a way for our extension to load these cookies into the browser automatically, I do not see a way how the DAA CCPA Opt Out Tool for the Web can be implemented.

(cc'ing @davebaraka and @rgoldstein01)

**Comment by SebastianZimmeck** [comment]
OK, I thought some more about this. Here is a plan (that hopefully works). 

1. Identify the 40 or so URLs that are used in the DAA extension (e.g., `choices.adhaven.com`), the cookie names (e.g., `optout`) and their values (e.g., `1`). Put all that information in a structured file (e.g., JSON) that can be read by our browser extension.
2. When the browser extension is installed by the user and runs for the first time, it will automatically visit all 40 URLs and place an opt out cookie per the JSON spec in the browser. A couple of things:
a. EditThisCookie is able to rewrite a cookie for a visited URL (see the screenshot below). We would need to automate this for each of the 40 sites.
b. Here is a JavaScript API for redirecting a browser to a particular site: [How to get the browser to navigate to URL in JavaScript.](https://stackoverflow.com/questions/1226714/how-to-get-the-browser-to-navigate-to-url-in-javascript). So, this API could potentially be used to visit each of the 40 sites. 
c. Finally, set a flag that the run is complete, e.g., just write a variable to `localStorage` of the browser extension. Now, every time the extension runs, check via an if-statement that the initial run of the 40 sites is complete.

<img width="1300" alt="Screen Shot 2020-07-06 at 10 33 15 AM" src="https://user-images.githubusercontent.com/11034003/86607976-f6273700-bf77-11ea-90e9-95f5a4b37198.png">

**Comment by kalicki1** [comment]
This looks like a good idea, and a good find! 

I will start to implement this alongside my work in issue #17, since the idea of storing variables in JSON, or other structured files, is related to another idea I had. Since it appears that different sites use either `usprivacy` or `us_privacy`, and potentially others, we could store these variations in a structured file similar to how you suggested we store references to these ad networks and third party cookies. I will try to implement this JSON approach over in issue #17 while I parse `us_privacy` cookie information stored on any given site, and then I will extend it here for your suggested DAA CCPA out-out approach.

**Comment by SebastianZimmeck** [comment]
As @kalicki1 remarked, due to the same origin policy it may be necessary to navigate to the particular site where we want to place the cookie. Ideally, this would work without visible browser action (i.e., opening a tab, navigating to a particular URL), but it may not be possible. One option would be to use some kind of [headless browser functionality](https://www.keycdn.com/blog/headless-browsers) (phantom.js, maybe). However, this would be some pretty heavy-handed approach and it is not clear that it would work either. 

Alternatively, traversing the DAA sites could be just an option or experimental mode function. Designating it as such would make it clear to users that this is not a polished standard functionality. There could also be special notifications. Overall, this approach would alleviate the not-so-nice functionality via usability measures.

**Comment by kalicki1** [comment]
With some further testing, it turns out that it is in fact possible to place the cookies we want to add from the extension's background page. The last commit adds this functionality for all of the cookies saved in the `cookies_3p.json` file. Here are some specifics: 

- Currently, the json saves only a 3rd party's cookie's name, value, and domain. From here, the extension generates a url to save the cookie in the form of `https://${cookie_domain}/`, after we ensure the domain is current-site specific (no `.` at the beginning of the domain string). 
- Since we will have the domains of the cookies saved to the json, the extension makes note of whether the json specifies a cookie should be set to a particular domain or all of its subdomains and sets the opt-out cookie accordingly. 
- Certain domains do not seem to have visitable urls, such as `https://ipredictive.com/`. I receive a 'site cannot be reached' error when I try to. Since the site cannot be reached, there doesn't seem to be a way for me to check if a cookie is ever set. 

Here are some screenshots:

<img width="600" alt="Screen Shot 2020-07-14 at 1 42 27 PM" src="https://user-images.githubusercontent.com/60238705/87459289-340c0700-c5d9-11ea-8606-da6b0ff6f91a.png">
<img width="600" alt="Screen Shot 2020-07-14 at 1 43 48 PM" src="https://user-images.githubusercontent.com/60238705/87459339-42f2b980-c5d9-11ea-9fa9-ab4554cd3654.png">
<img width="600" alt="Screen Shot 2020-07-14 at 1 46 00 PM" src="https://user-images.githubusercontent.com/60238705/87459314-3a01e800-c5d9-11ea-89f4-4e57e8ecc3db.png">
<img width="600" alt="Screen Shot 2020-07-14 at 1 46 58 PM" src="https://user-images.githubusercontent.com/60238705/87459321-3bcbab80-c5d9-11ea-9edc-e2ad2d39d07b.png">

1. The first screenshot basically shows what I explained in the notes above. There just didn't seem to be a way to check if a cookie was set for `https://ipredictive.com/`.
2. The second screenshot for `choices.adhaven.com` show that a cookie was set according the json data, however since the site doesn't seem to be made for consumers, there is no way to verify the site can read the cookie. 
3. The third screenshot shows that `tynt.com` doesn't seem to be in use anymore, as it redirects to another site. However, the cookie info from the json still managed to place a cookie on this intermediate site. 
4. `33across.com` is the redirect from `tynt.com`. The site in the screenshot is not the exact redirect url, though I managed to find the above `optout.33across.com` by manually browsing the homepage for the site. You can see above that at point 1, the site recognizes that the opt-out cookie is set in the browser. Point 2 also reaffirms this, and it actually changes values from 'Opt-In Now' to 'Opt-Out Now' if you delete the cookie and refresh the page. Clicking the link will set the same cookie our extension sets automatically. 

**Overall**
Besides the issue with verifying `https://ipredictive.com/`, it seems like this functionality is in fact possible! Minor tweaks maybe necessary in the future, especially once we start manually updating the data on the 3rd party cookies in our json file. This includes potentially explicitly specifying a valid URL for each opt-out cookie.

**Comment by kalicki1** [comment]
@SebastianZimmeck, a minor thought that occurred to me while I was updating the 3rd party cookie information in our JSON file was that if an ad network catches on to the fact that users are automating their company-specific opt-out process, they could change their cookie just enough to break the ones that are set by our extension. We would not have a way to make sure this ever happened. I suspect this may be out of our control for now, and might be a thought for another day.

**Comment by SebastianZimmeck** [comment]
> Certain domains do not seem to have visitable urls, such as https://ipredictive.com/. I receive a 'site cannot be reached' error when I try to. Since the site cannot be reached, there doesn't seem to be a way for me to check if a cookie is ever set.

Not sure how to go about this. But if you do a [whois](https://www.whois.com/whois/ipredictive.com) search, you will find that the domain is used by Adelphic, an ad network (demand side). Also, using the [DAA tool](https://optout.privacyrights.info/?c=1) and opting out from Adelphic, the opt out cookie is set on that domain. Ideally, we would be able to set the cookie as well.

**Comment by SebastianZimmeck** [comment]
>  however since the site doesn't seem to be made for consumers, there is no way to verify the site can read the cookie.
Apart from for whom the site is intended, are there doubts from a technical perspective?

Many of the sites will just be server domains not intended for anyone's visit. However, as long as a cookie is set properly to that domain, I see generally no problem. Maybe, there is a difference because of visiting the domain via a browser as opposed to just sending an HTTP request; not sure, though.

> 33across.com is the redirect from tynt.com

Similar thing as with ipredictive and Adelphic would also look into this via the [DAA tool](https://optout.privacyrights.info/?c=1) and whois.

**Comment by SebastianZimmeck** [comment]
> Besides the issue with verifying https://ipredictive.com/, it seems like this functionality is in fact possible!

Excellent!

**Comment by kalicki1** [comment]
Just to wrap up the discussion from above: 

> Certain domains do not seem to have visitable urls, such as https://ipredictive.com/. I receive a 'site cannot be reached' error when I try to. Since the site cannot be reached, there doesn't seem to be a way for me to check if a cookie is ever set.


@SebastianZimmeck, as we discussed during our meeting, I managed to figure out that the opt-out cookie for `https://ipredictive.com/` does manage to get set through our own DAA implementation. When I checked again for the site's cookies with EditThisCookie instead of the Chrome Debugger I was able to view them. This means that this implementation should be sound for now.

**Comment by kalicki1** [comment]
**Final thoughts on the ipredictive/Adelphic issue**
As for the other issue regarding different companies owning different services/sites (ipredictive and Adelphic), I think our current implementation will work for this case. It is interesting to note that the relationship between the different sites and services is more complex than I anticipated, though I think that as long as we maintain our 3rd party cookie list with all the relevant sites, we should be covering all our bases. This can mean that if we find out there is an opt-out cookie for a service, that we just add it to the list. I think it would be safer to add to the list than to remove cookies we are unsure about. 

**New issues and merging this issue**
Finding custom 3rd party cookies and adding them to our list can be its own issue. At this point, since our DAA CCPA opt-out functionality is working at a pretty good level, we can merge this into the master branch and continue to test it there alongside the rest of our code. I will open a pull request to finalize this issue and then close it out. We can continue to reference this issue in the future if we need to revisit problems we have already talked about.
