### ISSUE TITLE
Test the DAA CCPA Opt Out Tool for the Web

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#53]
For the WPES paper, we also would like to test the DAA CCPA opt out similar to the IAB test (issue #52). However, because the participating companies in the opt out tool are a limited set (100 or so per https://optout.privacyrights.info/?c=1), the approach is a bit different than for the IAB. Essentially, the idea here is to pick 20 (e.g., the first 20 or a random set of 20; either way works) and test whether OptMeowt will place an opt out cookie just as https://optout.privacyrights.info/?c=1 does. More specifically, here is the analysis procedure for each of the 20 selected companies:
1. On a fresh browser with no cookies, no extensions enabled, and default privacy settings (especially, allowing third party cookies), run https://optout.privacyrights.info/?c=1, opt out from the sale, and observe which cookie and value is set to the opt out.
2. Run OptMeowt and observe whether it is able to place and store the the identified cookie per the previous step in exactly the same manner as it would happen via https://optout.privacyrights.info/?c=1. 

It is not necessary to change any companies as in #52 if it does not work for one or some of them. The important thing is simply that it works for the 20 picked. So, if one does not work, @kalicki1, you can just keep testing on that until it works, then move to the next until all 20 work.

@kalicki1 made two interesting observations:
1. OptMeowt may be able to place third party opt out cookies despite the browser having third party cookies being disabled. This would be great because it would mean that privacy-conscious users can opt out *and* disable third party cookies at the same time. The reason may be that a browser extension may have more privileges than a site. @kalicki1, if this finding is confirmed in your tests, let's discuss more what the reason for this might be.
2. The DAA opt out via https://optout.privacyrights.info/?c=1 may not work for some of the companies. This finding in itself is an interesting result, especially, if confirmed for many companies involved. If confirmed, this too would be interesting to explore further and find why that is the case (e.g., is the problem on the company's end or with the DAA tool?)

Also, the list of cookies and cookie values that the companies are using in the DAA tool would be interesting to share with the community in the appendix to the paper.

(cc'ing @rgoldstein01 and @davebaraka)

**Comment by kalicki1** [comment]
After a call with @SebastianZimmeck yesterday, I began looking into this issue and compiled a document with information about the DAA tool and the third party cookies we want to use to opt-out of the sale of users' data. The [Google document is linked here](https://docs.google.com/document/d/1Z5DgutYIJoSGxWxz99XbGTFQiJhZOXZL1OfIfhtzYaI/edit?usp=sharing). 

At the moment I have a section for future OptMeowt suggestions related to this issue, a summary chart as @SebastianZimmeck recommended above, as well as a more thorough description of my methodology to find out what cookies each company is using and whatever results I found.

**Comment by kalicki1** [comment]
### Results for the first 10 DAA Companies
I began to look into the first 10 companies listed on the [DAA CCPA Opt-Out Tool](https://optout.privacyrights.info/?c=1), and currently I have found concrete opt-out cookies for 6/10 of the companies (with one of the successful cases potentially being a special case requiring additional work done by OptMeowt in 'real world' use cases). 

**Special Case regarding AuDigent and deleting cookies as well as placing opt-out cookies**
In short, if for some reason a user visits the AuDigent site before we place its opt-out cookie, the AuDigent will generate all of its usual website cookies and this will cause opt-out issues. This is because the opt-out cookie seems to only be a flag to generate the rest of AuDigent's cookies, one of which actually represents a user's choice to opt-out. This given id cookie, if placed on the site, indicates a user has 'opted-in' to the sale of their data, while the absense of this cookie indicates that they have 'opted-out'. This is unexpected behavior that complicates this situation a little in the real world use case of OptMeowt, though for the purposes of our paper, the assumption that we have a wiped browser and OptMeowt is loaded immediately sidesteps the issue and lets this 'flag' opt-out cookie be placed before anything else can be generated. Hence, I ultimately counted this as a success. 

**Unsuccessful cases**
For some of these four companies, I was unable to find whether or not the DAA tool actually set cookies to the sites they linked. This can be a combination of the fact that some cookies for these companies might be set to totally different domains, the fact that the given company's site has no way to check if you are 'opted-out' (some only provide opt-out forms not switches or notices), or even that the tool itself might not work. It is hard to tell. 

In other cases, I was able to cross-reference with the [NAI tool](https://optout.networkadvertising.org/?c=1) which seemed to be more reliable than the DAA in my limited testing (it also recognized if you are opted-out). I will continue to look into these four cases, though in the meantime it is good to note what I found here for future reference. 

**Summary**
For our 6 successful cases, I found concrete cookies, that when set, verifiably opt a user out of the sale of their data. We can write about these in our paper and describe how, as long as we can identify what cookies opt a user out and give those cookies to OptMeowt, OptMeowt will be able to place them and verifiably opt a user out. This explanation also provides a way out of our 'unsuccessful' cases, since it is not an issue with OptMeowt being faulty but rather an inability to isolate how a given company's opt-out mechanism works.
