### ISSUE TITLE
Add functionality for placing usprivacy third party cookies for the IAB CCPA Compliance Framework

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#54]
@kalicki1 implemented opting out for the IAB CCPA Compliance Framework (issue #17). The most common use case is the `usprivacy` string in a first party cookie. However, there are also sites with third party cookies using the `usprivacy` string. Thus, depending how far we want to go implementing the IAB CCPA Compliance Framework, it may be worthwhile to have functionality for setting the `usprivacy` string for third party cookies as well.

**Comment by kalicki1** [comment]
@SebastianZimmeck, since we have implemented our custom headers and custom cookies functionality in issue #45, I feel that if a user chooses to implement 3rd party IAB cookies they could use our custom cookie YAML lists and update these IAB cookies there. In this case, this issue should be resolved. What are your thoughts on this?

**Comment by SebastianZimmeck** [comment]
@kalicki1, agreed! You are making a very good point here.
