### ISSUE TITLE
Update the About page

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#57]
As discussed earlier today, I will make some major changes to the Domain List as mentioned in issue #56. Along with this, @SebastianZimmeck and I discussed updating the language of the About page, which should include, amongst other changes:

A link to our Landing Page (GitHub link)
A link to our extension in the Chrome Web Store
A link to the privacy-tech-lab site
A link to our technical documentation
Contact details (Our emails, Wesleyan, privacy-tech-lab, etc.)
A notification to check for extension updates

In general this relates to issue #55.

**Comment by kalicki1** [comment]
@SebastianZimmeck, I uploaded a draft `About` page here. It might be a little bit verbose, let me know if you think we should shrink it down to, for example, just a list of links.

**Comment by SebastianZimmeck** [comment]
I like the Q&A style.

> let me know if you think we should shrink it down to, for example, just a list of links.

Yes, making it a bit shorter and simpler would be good. Though, I do not think it should be just a list of links. But the language should be more to the point and less technical. Just one question and one answer sentence. E.g., 

> Who are you? We are academic researchers at the <a href="https://privacy-tech-lab.github.io/"> Wesleyan University privacy-tech-lab</a>.

Also, I do not think that we need to mention the landing page. It would work the other way around. People find the landing page and come to the extension. Maybe, instead of the landing page you can have an item like

> Do I need to have an account? You do not need an account <link to user sign up>, but if you have one, you can sync your domain list across devices.

**Comment by kalicki1** [comment]
I simplified the about page just a bit in the recent commit. @SebastianZimmeck let me know if there is anything else I should change, and I think we can merge this into the master branch.

**Comment by SebastianZimmeck** [comment]
Sounds good. Feel free to open a PR. We can still make some smaller changes later on.

**Comment by SebastianZimmeck** [comment]
This seems done to me. Please reopen if necessary, @kalicki1.
