### ISSUE TITLE
Fix display of long domain names in popup

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#67]
Currently the popup only displays part of long domain names (per below the domain for OptMeow, for example). Ideally, we would like to break long domain names into multiple lines. If that is not possible, maybe truncated domain names.

<img width="346" alt="Screen Shot 2020-08-15 at 11 01 41 AM" src="https://user-images.githubusercontent.com/11034003/90315104-bba1aa00-dee6-11ea-9a14-89f683a519c2.png">

**Comment by kalicki1** [comment]
The main functionality should be uploaded above, though I will double check my locally saved code to see if there any further updates that weren't finalized when I was working on this issue. Once I upload those, this issue should be closed.

**Comment by SebastianZimmeck** [comment]
@asalia-1 is suggesting to not show the domain in the popup if there is no real URL (like extension IDs, localhost, ...). Technically, this is the case when no Do Not Sell signal should be sent. When the URL is parsed for the URL and the domain returns null, these are the cases where this should not be shown.

**Comment by asalia-1** [comment]
Worked with Kuba to remove  `send do not sell` switch and domain as discussed when url does not connect to resource on web 
(for example chrome://extensions). See the photo below to show what that looks like. 

![dns-removal](https://user-images.githubusercontent.com/44120238/91899309-f176ba80-ec6a-11ea-8c1d-18376d59fd2d.jpg)

**NB:** The responses section in the pop up will be updated once this issue is merged with issue #63

**Comment by SebastianZimmeck** [comment]
@asalia-1, please close this issue if this is resolved now (or write what is still outstanding).
