### ISSUE TITLE
Connect OptMeowt to reference Do Not Sell backend implementations

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#70]

**Comment by SebastianZimmeck** [comment]
I created various stubs for backends using web frameworks that can be used to implement [SPOC](https://github.com/darobin/spoc):

https://github.com/privacy-tech-lab/django-reference-project
https://github.com/privacy-tech-lab/express-reference-project

Whatever API is exposed there in the end, needs to be connected to OptMeowt. So we need to work from both sides --- the web server and the OptMeowt extension/browser end --- and connect the two.

(While the Firebase discussion we had earlier is not 100% related to these points, as Firebase was more for the OptMeowt backend and not for the SPOC backend, I am still inclined to use whatever technologies we us to implement SPOC to use for any OptMeowt functionality as well.

**Comment by SebastianZimmeck** [comment]
Once the smaller issues are out of the way that we discussed earlier this week, this issue is the most important one. Essentially, we can mirror DuckDuckGo's solution:

1. [Frontend code](https://github.com/duckduckgo/duckduckgo-privacy-extension/compare/dharb/do-not-sell) to be included in the [DuckDuckGo Privacy Essentials extension](https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg). Here is a [zipped beta dev of the extension that already includes the Do Not Sell functionality](https://github.com/globalprivacycontrols/gpc-spec/issues/22#issuecomment-690589743).
2. [Backend server implementation](https://global-privacy-control.glitch.me/). We have two blank sample Heroku servers that we may be able to use (or not): [Django/Python](https://github.com/globalprivacycontrols/django-reference-project) (running [here](https://django-reference-project.herokuapp.com/)), [Express/Node.js](https://github.com/globalprivacycontrols/express-reference-project) (running [here](https://express-reference-project.herokuapp.com/)).

I have not yet looked into details of the DuckDuckGo code. Let's take a look at it and ask for any clarification.

**Comment by kalicki1** [comment]
I opened a new issue for this accidentally, but I will work on this here. Three things I want to work on implementing are support for: 

- [ ] GPC header
- [ ] GPC DOM signal
- [ ] `.well-known/GPC`

**Comment by SebastianZimmeck** [comment]
@kalicki1 is describing that the use of the `fetch` API in OptMeowt causes a loop that keeps requesting data from the `.well-known` API. Maybe, this can be resolved with the general issue here (#11); maybe also not. @kalicki1 and @asalia-1 will look into this.

**Comment by kalicki1** [comment]
I just pushed some initial code that checks for a website's `.well-known\GPC` at the requested URLs origin. We can make this check more frequent, or even for each request, though I didn't think that would be necessary in this version. For now, if the `.well-known\GPC` exists, it is printed to the console.

**Comment by kalicki1** [comment]
Given that the main functionality this issue was about has been implemented, I think we are free to open a pull request on this issue. This will help us finalize our code for an initial Chrome Web Store launch, as @SebastianZimmeck mentioned earlier today.

**Comment by SebastianZimmeck** [comment]
> I think we are free to open a pull request on this issue.

Excellent! Feel free to go ahead once you are ready.

**Comment by SebastianZimmeck** [comment]
@kalicki1, can you close this issue when it is done?
