### ISSUE TITLE
Opt out signal not detected on GPC landing page

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#92]
It seems that the [landing page](https://globalprivacycontrol.org/) does not detect OptMeowt's GPC signal. When I visit it (on the current Brave browser with ad blocking turned off), I am seeing the following. 

<img width="475" alt="Screen Shot 2020-10-07 at 7 55 47 AM" src="https://user-images.githubusercontent.com/11034003/95327790-92602300-0872-11eb-8154-c318f3510f40.png">

Probably, @kalicki1 is in the best position to address this issue. But if you, @asalia-1 or @dknopf, want to give it a go, feel free.

**Comment by SebastianZimmeck** [comment]
Not sure, possibly @dharb could also provide some info where the issue may be.

**Comment by dharb** [comment]
Right now that indicator is just checking if the DOM signal is set, we punted on hooking up a header check until post launch due to time crunch. Eg `if (navigator.globalPrivacyControl) { success }`. OptMeowt must not be setting that signal, see https://gist.github.com/dharb/15bb3888c258d15cf96efec9b72dd605#setting-the-dom-signal for approach.

**Comment by dharb** [comment]
@SebastianZimmeck @kalicki1 if you just change [this line](https://github.com/privacy-tech-lab/optmeowt-browser-extension/blob/master/src/dom.js#L2) to use `navigator` instead of `window` it should fix things. Two things to keep in mind though:
- You should wrap `Object.defineProperty...` in a try catch block. If that property has already been set by a different extension with `writable: false` that will throw an error.
- Adding a script tag to the DOM like that can be blocked by a site's CSP in Firefox (for instance, on twitter.com). Check out the section in the gist I shared about Xray vision for details.

**Comment by kalicki1** [comment]
@dharb good catch, I updated the `navigator` line our code base. I will take a look at updating the other things you brought up as well, they are great suggestions. 

The only thing I'm worried about now is that even with the `navigator` change, the landing page seems to recognize our DOM signal when I open a new tab and visit the site, though subsequent refreshes seem to kick it back to not recognizing the signal. My guess as to why is that our extension just loads the signal right after the site checks for it and its a timing issue. I'm not sure if you would know what this could be related to, but I will take a look as well.

**Comment by dharb** [comment]
@kalicki1 I just took a look and it appears that you're injecting the content script in the `addHeaders` function, which is being called by the `chrome.webRequest.onBeforeSendHeaders` listener: https://github.com/privacy-tech-lab/optmeowt-browser-extension/blob/master/src/background.js#L221. Maybe try injecting the dom signal using `chrome.webNavigation.onCommitted` instead?

**Comment by SebastianZimmeck** [comment]
Very nice work, @kalicki1! The signal is now detected on the [site](https://globalprivacycontrol.org/). I released a new version v1.0.1 with this bug fix and submitted it to the Chrome Web Store as well. It should be up there soon.

Thanks a bunch, @dharb!
